### ISSUE TITLE
bad metadata

### ISSUE THREAD

**Issue by plicease** [wbraswell/alien-astyle#1]
The links from metacpan are broken because `-latest` has been appended in the `META.yml` file:

https://metacpan.org/source/WBRASWELL/Alien-astyle-0.001000/META.yml#L21

Not sure why, the Build.PL seems to have set them correctly.

**Comment by wbraswell** [comment]
Perhaps I somehow manually set these incorrectly?
Either way, I have fixed it in v0.002, now on CPAN!  :-)
https://metacpan.org/release/WBRASWELL/Alien-astyle-0.002000
